# 项目相关配置
ginyon:
  # 名称
  name: ginyon-iot-tenant
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2025
  # 实例演示开关
  demoEnabled: false
  # 获取ip地址开关
  addressEnabled: false
  # 文件路径 示例（ Windows配置D:/gioyon/uploadPath，Linux配置 /home/ginyon/uploadPath  通用相对路径（当前目录） ./uploadPath 或 uploadPath）
  profile: ./uploadPath

captcha:
  enable: true
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

server:
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: @profiles.active@
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .ftlh  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      default_encoding: 'UTF-8'
      number_format: '0.##'   #数字格式化，无小数点
      classic_compatible: true
      url_escaping_charset: 'UTF-8'
      template_update_delay: 0
      output_encoding: 'UTF-8'
      locale: 'zh_CN'
      date_format: 'yyyy-MM-dd'
      datetime_format: 'yyyy-MM-dd HH:mm:ss'

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token前缀
  token-prefix: Bearer
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否在初始化配置时在控制台打印版本字符画
  isPrint: false
  # jwt秘钥
  jwt-secret-key: abcdefghijklmnopqrstuvwxyz

# security配置
security:
  # 排除路径
  excludes:
    # 静态资源
    - /*.html
    - /**/*.html
    - /**/*.css
    - /**/*.js
    - /profile/**
    # swagger 文档配置
    - /swagger-ui.html
    - /swagger-ui/**
    - /swagger-resources/**
    - /webjars/**"
    - /*/api-docs
    - /*/api-docs/**
    - /druid/**


# MyBatis-plus配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.ginyon.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # 启动时是否检查 MyBatis XML 文件的存在，默认不检查
  checkConfigLocation: false
  configuration:
    # 自动驼峰命名规则（camel case）映射
    mapUnderscoreToCamelCase: true
  global-config:
    # 是否打印 Logo banner
    banner: false
    dbConfig:
      # 主键类型
      # AUTO 自增 NONE 空 INPUT 用户输入 ASSIGN_ID 雪花 ASSIGN_UUID 唯一 UUID
      # 如需改为自增 需要将数据库表全部设置为自增
      idType: ASSIGN_ID
      # 逻辑已删除值(框架表均使用此值 禁止随意修改)
      logicDeleteValue: 2
      # 逻辑未删除值
      logicNotDeleteValue: 0
      insertStrategy: NOT_NULL
      updateStrategy: NOT_NULL
      whereStrategy: NOT_NULL

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 多租户配置
tenant:
  # 是否开启
  enable: true
  # 排除表
  excludes:
    - sys_menu
    - sys_tenant
    - sys_tenant_package
    - sys_role_dept
    - sys_role_menu
    - sys_user_post
    - sys_user_role
    - gen_table
    - gen_table_column
    - flow_definition
    - flow_node
    - flow_skip
    - flow_instance
    - flow_his_task
    - flow_task
    - qrtz_blob_triggers
    - qrtz_calendars
    - qrtz_cron_triggers
    - qrtz_fired_triggers
    - qrtz_job_details
    - qrtz_locks
    - qrtz_paused_trigger_grps
    - qrtz_scheduler_state
    - qrtz_simple_triggers
    - qrtz_simprop_triggers
    - qrtz_triggers
